# DBSRV Account default directory
DBSRVRoot=D:\\WYD_MIizael\\Engine_SourceCliente\\MythServerRelease\\DataServer\\account\\

# Server PIN Code default directory
ImportUser=D:\\WYD_MIizael\\Engine_SourceCliente\\MythServerRelease\\DataServer\\ImportUser\\

ImportUserLogFile=D:\\WYD_MIizael\\Engine_SourceCliente\\MythServerRelease\\ApiServer\\Logs\\ImportAccount.txt
