;Evol 0 = mortal 1 = arch 2 = cele 3 = sub
;Maximo de configuracoes = 200
;Type 1 = por evolucao 2 = por mapa
;ExpMult pode ser de -990 (Diminuir) ate ao infinito e alem

;Mortal lv 0 ao 400 recebe penalidade de 100% na exp
[Conf_0]
Type=1
Evol=0
ExpMult=1500
LevelMin=0
LevelMax=400


;Arch lv 0 ao 400 recebe bonus de 100.0% na exp
[Conf_2]
Type=1
Evol=1
ExpMult=1500
LevelMin=0
LevelMax=400

;Celestial lv 0 ao 200 recebe bonus de 100% na exp
[Conf_3]
Type=1
Evol=2
ExpMult=1
LevelMin=0
LevelMax=200

[Conf_4]
Type=1
Evol=3
ExpMult=1
LevelMin=0
LevelMax=202

[Conf_5]
Type=2
Evol=2
ExpMult=1000
MinX=1173
MinY=1710
MaxX=1200
MaxY=1735

;Configuracao por zona (celestial pilar) +100.0%
[Conf_6]
Type=2
Evol=3
ExpMult=1000
MinX=1173
MinY=1710
MaxX=1200
MaxY=1735
